service: lbh-social-care

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: eu-west-2
  stage: ${opt:stage}

package:
  individually: true
  exclude:
    - ./**

functions:
  lbh-social-care:
    name: ${self:service}-${self:provider.stage}
    handler: lambda.handler
    timeout: 30
    package:
      patterns:
        - 'lambda.js'
        - 'next.config.js'
        - 'pages/**'
        - 'public/**'
        - 'build/_next/**'
        - 'node_modules/**'
        - '!build/_next/cache/**'

    events:
      - http:
          path: api/{proxy+}
          method: ANY
      - http: ANY /
      - http: ANY /{proxy+}
    provisionedConcurrency: 5
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:provider.stage}}
      subnetIds: ${self:custom.subnets.${self:provider.stage}}
    environment:
      NEXT_PUBLIC_ENV: ${opt:stage}
      AWS_KEY: ${ssm:/lbh-social-care/${self:provider.stage}/aws-key}
      ENDPOINT_API: ${ssm:/lbh-social-care/${self:provider.stage}/endpoint-case-viewer}
      GSSO_URL: ${ssm:/lbh-social-care/${self:provider.stage}/gsso-url}
      GSSO_TOKEN_NAME: ${ssm:/lbh-social-care/${self:provider.stage}/gsso-token-name}
      HACKNEY_JWT_SECRET: ${ssm:/lbh-social-care/${self:provider.stage}/hackney-jwt}
      AUTHORISED_DEV_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-dev-group}
      AUTHORISED_ADMIN_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-admin-group}
      AUTHORISED_ADULT_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-adult-group}
      AUTHORISED_CHILD_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-child-group}
      AUTHORISED_ALLOCATORS_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-allocators-group}
      AUTHORISED_UNRESTRICTED_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-unrestricted-group}
      AUTHORISED_AUDITABLE_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-auditable-group}
      POSTCODE_LOOKUP_URL: ${ssm:/lbh-social-care/${self:provider.stage}/postcode-lookup-url}
      POSTCODE_LOOKUP_APIKEY: ${ssm:/lbh-social-care/${self:provider.stage}/postcode-lookup-apikey}
      NEXT_PUBLIC_FEEDBACK_LINK: ${ssm:/lbh-social-care/${self:provider.stage}/next-public-feedback-link}
      REDIRECT_URL: ${ssm:/lbh-social-care/${self:provider.stage}/redirect_url}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${ssm:/lbh-social-care/${self:provider.stage}/next_public_google_analytics_id}
      NEXT_PUBLIC_SENTRY_DSN: ${ssm:/lbh-social-care/${self:provider.stage}/next-public-sentry-dsn}
      NEXT_PUBLIC_SENTRY_TARGET: ${ssm:/lbh-social-care/${self:provider.stage}/next-public-sentry-target}
      SENTRY_DSN: ${ssm:/lbh-social-care/${self:provider.stage}/sentry-dsn}
      SENTRY_TARGET: ${ssm:/lbh-social-care/${self:provider.stage}/sentry-target}
      NOTIFY_API_KEY: ${ssm:/lbh-social-care/${self:provider.stage}/notify-api-key}
      NOTIFY_APPROVER_TEMPLATE_ID: ${ssm:/lbh-social-care/${self:provider.stage}/notify-approver-template-id}
      NOTIFY_RETURN_FOR_EDITS_TEMPLATE_ID: ${ssm:/lbh-social-care/${self:provider.stage}/notify-return-for-edits-template-id}
      WORKFLOWS_PILOT_URL: ${ssm:/lbh-social-care/${self:provider.stage}/workflows-pilot-url}
      AUTHORISED_WORKFLOWS_PILOT_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-workflows-pilot-group}
      AUTHORISED_SAFEGUARDING_REVIEWING_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-safeguarding-reviewing-group}
      AUTHORISED_PLACEMENT_MANAGEMENT_UNIT_GROUP: ${ssm:/lbh-social-care/${self:provider.stage}/authorised-placement-management-unit-group}
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  aliases:
    staging: social-care-service-staging.hackney.gov.uk
    production: social-care-service-alb-temp-non-existent.hackney.gov.uk
    mosaic-prod: social-care-service.hackney.gov.uk
  certificate-arn:
    staging: arn:aws:acm:us-east-1:715003523189:certificate/d2860eaf-cd6a-46e8-a171-2edc3450a51c
    production: arn:aws:acm:us-east-1:153306643385:certificate/71728a39-cd3e-4570-a440-e87f84ef9a0d
    mosaic-prod: arn:aws:acm:us-east-1:267112830674:certificate/dae4d0be-8f3a-4512-ba9c-fb80366e77f7
  securityGroups:
    staging:
      - sg-048f0fb9620e30710
    production:
      - sg-082581136513324b1
    mosaic-prod:
      - sg-0d92164e9f5d53800
  subnets:
    staging:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
    production:
      - subnet-0b7b8fea07efabf34
      - subnet-01d3657f97a243261
    mosaic-prod:
      - subnet-0c39cd286eeaff2b2
      - subnet-04c42d0aafb3738ad
